query ($status: String!) {
  characters (filter: {status: $status}) {
    results {
      name
      id
      image
      status
      species
      origin {
        name
      }
      location {
        name
      }
    }
  }
}
